namespace csharp_lksmart
{
    partial class FAdminLaporan
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FAdminLaporan));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea1 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend1 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series1 = new System.Windows.Forms.DataVisualization.Charting.Series();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.dateEnd = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.btnLogout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLogActivity = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnKelolaLaporan = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dateStart = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuLabel11 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnReset = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnFilter = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dataGridViewLaporan = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnKelolaUser = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.chartOmset = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.btnGenerate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewLaporan)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.bunifuPanel2.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.chartOmset)).BeginInit();
            this.SuspendLayout();
            // 
            // dateEnd
            // 
            this.dateEnd.BackColor = System.Drawing.Color.Transparent;
            this.dateEnd.BorderRadius = 1;
            this.dateEnd.Color = System.Drawing.Color.Silver;
            this.dateEnd.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dateEnd.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dateEnd.DisabledColor = System.Drawing.Color.Gray;
            this.dateEnd.DisplayWeekNumbers = false;
            this.dateEnd.DPHeight = 0;
            this.dateEnd.FillDatePicker = false;
            this.dateEnd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dateEnd.ForeColor = System.Drawing.Color.Black;
            this.dateEnd.Icon = ((System.Drawing.Image)(resources.GetObject("dateEnd.Icon")));
            this.dateEnd.IconColor = System.Drawing.Color.Gray;
            this.dateEnd.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dateEnd.LeftTextMargin = 5;
            this.dateEnd.Location = new System.Drawing.Point(548, 115);
            this.dateEnd.MinimumSize = new System.Drawing.Size(0, 32);
            this.dateEnd.Name = "dateEnd";
            this.dateEnd.Size = new System.Drawing.Size(220, 32);
            this.dateEnd.TabIndex = 27;
            // 
            // btnLogout
            // 
            this.btnLogout.AllowAnimations = true;
            this.btnLogout.AllowMouseEffects = true;
            this.btnLogout.AllowToggling = false;
            this.btnLogout.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnLogout.AnimationSpeed = 200;
            this.btnLogout.AutoGenerateColors = false;
            this.btnLogout.AutoRoundBorders = false;
            this.btnLogout.AutoSizeLeftIcon = true;
            this.btnLogout.AutoSizeRightIcon = true;
            this.btnLogout.BackColor = System.Drawing.Color.Transparent;
            this.btnLogout.BackColor1 = System.Drawing.Color.Crimson;
            this.btnLogout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLogout.BackgroundImage")));
            this.btnLogout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.ButtonText = "Logout";
            this.btnLogout.ButtonTextMarginLeft = 0;
            this.btnLogout.ColorContrastOnClick = 45;
            this.btnLogout.ColorContrastOnHover = 45;
            this.btnLogout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnLogout.CustomizableEdges = borderEdges1;
            this.btnLogout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLogout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLogout.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.btnLogout.ForeColor = System.Drawing.Color.White;
            this.btnLogout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLogout.IconMarginLeft = 11;
            this.btnLogout.IconPadding = 10;
            this.btnLogout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLogout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLogout.IconSize = 25;
            this.btnLogout.IdleBorderColor = System.Drawing.Color.Crimson;
            this.btnLogout.IdleBorderRadius = 15;
            this.btnLogout.IdleBorderThickness = 1;
            this.btnLogout.IdleFillColor = System.Drawing.Color.Crimson;
            this.btnLogout.IdleIconLeftImage = null;
            this.btnLogout.IdleIconRightImage = null;
            this.btnLogout.IndicateFocus = false;
            this.btnLogout.Location = new System.Drawing.Point(64, 457);
            this.btnLogout.Name = "btnLogout";
            this.btnLogout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogout.OnDisabledState.BorderRadius = 15;
            this.btnLogout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.OnDisabledState.BorderThickness = 1;
            this.btnLogout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogout.OnDisabledState.IconLeftImage = null;
            this.btnLogout.OnDisabledState.IconRightImage = null;
            this.btnLogout.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(23)))), ((int)(((byte)(54)))));
            this.btnLogout.onHoverState.BorderRadius = 15;
            this.btnLogout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.onHoverState.BorderThickness = 1;
            this.btnLogout.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(23)))), ((int)(((byte)(54)))));
            this.btnLogout.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLogout.onHoverState.IconLeftImage = null;
            this.btnLogout.onHoverState.IconRightImage = null;
            this.btnLogout.OnIdleState.BorderColor = System.Drawing.Color.Crimson;
            this.btnLogout.OnIdleState.BorderRadius = 15;
            this.btnLogout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.OnIdleState.BorderThickness = 1;
            this.btnLogout.OnIdleState.FillColor = System.Drawing.Color.Crimson;
            this.btnLogout.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLogout.OnIdleState.IconLeftImage = null;
            this.btnLogout.OnIdleState.IconRightImage = null;
            this.btnLogout.OnPressedState.BorderColor = System.Drawing.Color.Crimson;
            this.btnLogout.OnPressedState.BorderRadius = 15;
            this.btnLogout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.OnPressedState.BorderThickness = 1;
            this.btnLogout.OnPressedState.FillColor = System.Drawing.Color.Crimson;
            this.btnLogout.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLogout.OnPressedState.IconLeftImage = null;
            this.btnLogout.OnPressedState.IconRightImage = null;
            this.btnLogout.Size = new System.Drawing.Size(176, 39);
            this.btnLogout.TabIndex = 22;
            this.btnLogout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLogout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLogout.TextMarginLeft = 0;
            this.btnLogout.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLogout.UseDefaultRadiusAndThickness = true;
            // 
            // btnLogActivity
            // 
            this.btnLogActivity.AllowAnimations = true;
            this.btnLogActivity.AllowMouseEffects = true;
            this.btnLogActivity.AllowToggling = false;
            this.btnLogActivity.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnLogActivity.AnimationSpeed = 200;
            this.btnLogActivity.AutoGenerateColors = false;
            this.btnLogActivity.AutoRoundBorders = false;
            this.btnLogActivity.AutoSizeLeftIcon = true;
            this.btnLogActivity.AutoSizeRightIcon = true;
            this.btnLogActivity.BackColor = System.Drawing.Color.Transparent;
            this.btnLogActivity.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnLogActivity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLogActivity.BackgroundImage")));
            this.btnLogActivity.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogActivity.ButtonText = "Log Activity";
            this.btnLogActivity.ButtonTextMarginLeft = 0;
            this.btnLogActivity.ColorContrastOnClick = 45;
            this.btnLogActivity.ColorContrastOnHover = 45;
            this.btnLogActivity.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnLogActivity.CustomizableEdges = borderEdges2;
            this.btnLogActivity.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLogActivity.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogActivity.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogActivity.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogActivity.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLogActivity.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.btnLogActivity.ForeColor = System.Drawing.Color.White;
            this.btnLogActivity.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogActivity.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogActivity.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLogActivity.IconMarginLeft = 11;
            this.btnLogActivity.IconPadding = 10;
            this.btnLogActivity.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLogActivity.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogActivity.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLogActivity.IconSize = 25;
            this.btnLogActivity.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnLogActivity.IdleBorderRadius = 15;
            this.btnLogActivity.IdleBorderThickness = 1;
            this.btnLogActivity.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnLogActivity.IdleIconLeftImage = null;
            this.btnLogActivity.IdleIconRightImage = null;
            this.btnLogActivity.IndicateFocus = false;
            this.btnLogActivity.Location = new System.Drawing.Point(64, 384);
            this.btnLogActivity.Name = "btnLogActivity";
            this.btnLogActivity.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogActivity.OnDisabledState.BorderRadius = 15;
            this.btnLogActivity.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogActivity.OnDisabledState.BorderThickness = 1;
            this.btnLogActivity.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogActivity.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogActivity.OnDisabledState.IconLeftImage = null;
            this.btnLogActivity.OnDisabledState.IconRightImage = null;
            this.btnLogActivity.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(130)))), ((int)(((byte)(171)))));
            this.btnLogActivity.onHoverState.BorderRadius = 15;
            this.btnLogActivity.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogActivity.onHoverState.BorderThickness = 1;
            this.btnLogActivity.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(130)))), ((int)(((byte)(171)))));
            this.btnLogActivity.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLogActivity.onHoverState.IconLeftImage = null;
            this.btnLogActivity.onHoverState.IconRightImage = null;
            this.btnLogActivity.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnLogActivity.OnIdleState.BorderRadius = 15;
            this.btnLogActivity.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogActivity.OnIdleState.BorderThickness = 1;
            this.btnLogActivity.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnLogActivity.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnLogActivity.OnIdleState.IconLeftImage = null;
            this.btnLogActivity.OnIdleState.IconRightImage = null;
            this.btnLogActivity.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnLogActivity.OnPressedState.BorderRadius = 15;
            this.btnLogActivity.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogActivity.OnPressedState.BorderThickness = 1;
            this.btnLogActivity.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnLogActivity.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLogActivity.OnPressedState.IconLeftImage = null;
            this.btnLogActivity.OnPressedState.IconRightImage = null;
            this.btnLogActivity.Size = new System.Drawing.Size(176, 39);
            this.btnLogActivity.TabIndex = 21;
            this.btnLogActivity.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLogActivity.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLogActivity.TextMarginLeft = 0;
            this.btnLogActivity.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLogActivity.UseDefaultRadiusAndThickness = true;
            // 
            // btnKelolaLaporan
            // 
            this.btnKelolaLaporan.AllowAnimations = true;
            this.btnKelolaLaporan.AllowMouseEffects = true;
            this.btnKelolaLaporan.AllowToggling = false;
            this.btnKelolaLaporan.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnKelolaLaporan.AnimationSpeed = 200;
            this.btnKelolaLaporan.AutoGenerateColors = false;
            this.btnKelolaLaporan.AutoRoundBorders = false;
            this.btnKelolaLaporan.AutoSizeLeftIcon = true;
            this.btnKelolaLaporan.AutoSizeRightIcon = true;
            this.btnKelolaLaporan.BackColor = System.Drawing.Color.Transparent;
            this.btnKelolaLaporan.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(110)))), ((int)(((byte)(180)))), ((int)(((byte)(239)))));
            this.btnKelolaLaporan.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnKelolaLaporan.BackgroundImage")));
            this.btnKelolaLaporan.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKelolaLaporan.ButtonText = "Kelola Laporan";
            this.btnKelolaLaporan.ButtonTextMarginLeft = 0;
            this.btnKelolaLaporan.ColorContrastOnClick = 45;
            this.btnKelolaLaporan.ColorContrastOnHover = 45;
            this.btnKelolaLaporan.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnKelolaLaporan.CustomizableEdges = borderEdges3;
            this.btnKelolaLaporan.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnKelolaLaporan.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnKelolaLaporan.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnKelolaLaporan.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnKelolaLaporan.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnKelolaLaporan.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.btnKelolaLaporan.ForeColor = System.Drawing.Color.White;
            this.btnKelolaLaporan.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnKelolaLaporan.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnKelolaLaporan.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnKelolaLaporan.IconMarginLeft = 11;
            this.btnKelolaLaporan.IconPadding = 10;
            this.btnKelolaLaporan.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnKelolaLaporan.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnKelolaLaporan.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnKelolaLaporan.IconSize = 25;
            this.btnKelolaLaporan.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(110)))), ((int)(((byte)(180)))), ((int)(((byte)(239)))));
            this.btnKelolaLaporan.IdleBorderRadius = 15;
            this.btnKelolaLaporan.IdleBorderThickness = 1;
            this.btnKelolaLaporan.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(110)))), ((int)(((byte)(180)))), ((int)(((byte)(239)))));
            this.btnKelolaLaporan.IdleIconLeftImage = null;
            this.btnKelolaLaporan.IdleIconRightImage = null;
            this.btnKelolaLaporan.IndicateFocus = false;
            this.btnKelolaLaporan.Location = new System.Drawing.Point(64, 333);
            this.btnKelolaLaporan.Name = "btnKelolaLaporan";
            this.btnKelolaLaporan.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnKelolaLaporan.OnDisabledState.BorderRadius = 15;
            this.btnKelolaLaporan.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKelolaLaporan.OnDisabledState.BorderThickness = 1;
            this.btnKelolaLaporan.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnKelolaLaporan.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnKelolaLaporan.OnDisabledState.IconLeftImage = null;
            this.btnKelolaLaporan.OnDisabledState.IconRightImage = null;
            this.btnKelolaLaporan.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(130)))), ((int)(((byte)(171)))));
            this.btnKelolaLaporan.onHoverState.BorderRadius = 15;
            this.btnKelolaLaporan.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKelolaLaporan.onHoverState.BorderThickness = 1;
            this.btnKelolaLaporan.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(130)))), ((int)(((byte)(171)))));
            this.btnKelolaLaporan.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnKelolaLaporan.onHoverState.IconLeftImage = null;
            this.btnKelolaLaporan.onHoverState.IconRightImage = null;
            this.btnKelolaLaporan.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(110)))), ((int)(((byte)(180)))), ((int)(((byte)(239)))));
            this.btnKelolaLaporan.OnIdleState.BorderRadius = 15;
            this.btnKelolaLaporan.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKelolaLaporan.OnIdleState.BorderThickness = 1;
            this.btnKelolaLaporan.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(110)))), ((int)(((byte)(180)))), ((int)(((byte)(239)))));
            this.btnKelolaLaporan.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnKelolaLaporan.OnIdleState.IconLeftImage = null;
            this.btnKelolaLaporan.OnIdleState.IconRightImage = null;
            this.btnKelolaLaporan.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(110)))), ((int)(((byte)(180)))), ((int)(((byte)(239)))));
            this.btnKelolaLaporan.OnPressedState.BorderRadius = 15;
            this.btnKelolaLaporan.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKelolaLaporan.OnPressedState.BorderThickness = 1;
            this.btnKelolaLaporan.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(110)))), ((int)(((byte)(180)))), ((int)(((byte)(239)))));
            this.btnKelolaLaporan.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnKelolaLaporan.OnPressedState.IconLeftImage = null;
            this.btnKelolaLaporan.OnPressedState.IconRightImage = null;
            this.btnKelolaLaporan.Size = new System.Drawing.Size(176, 39);
            this.btnKelolaLaporan.TabIndex = 21;
            this.btnKelolaLaporan.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnKelolaLaporan.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnKelolaLaporan.TextMarginLeft = 0;
            this.btnKelolaLaporan.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnKelolaLaporan.UseDefaultRadiusAndThickness = true;
            // 
            // dateStart
            // 
            this.dateStart.BackColor = System.Drawing.Color.Transparent;
            this.dateStart.BorderRadius = 1;
            this.dateStart.Color = System.Drawing.Color.Silver;
            this.dateStart.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dateStart.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dateStart.DisabledColor = System.Drawing.Color.Gray;
            this.dateStart.DisplayWeekNumbers = false;
            this.dateStart.DPHeight = 0;
            this.dateStart.FillDatePicker = false;
            this.dateStart.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dateStart.ForeColor = System.Drawing.Color.Black;
            this.dateStart.Icon = ((System.Drawing.Image)(resources.GetObject("dateStart.Icon")));
            this.dateStart.IconColor = System.Drawing.Color.Gray;
            this.dateStart.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dateStart.LeftTextMargin = 5;
            this.dateStart.Location = new System.Drawing.Point(314, 116);
            this.dateStart.MinimumSize = new System.Drawing.Size(0, 32);
            this.dateStart.Name = "dateStart";
            this.dateStart.Size = new System.Drawing.Size(220, 32);
            this.dateStart.TabIndex = 27;
            // 
            // bunifuLabel11
            // 
            this.bunifuLabel11.AllowParentOverrides = false;
            this.bunifuLabel11.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel11.AutoEllipsis = false;
            this.bunifuLabel11.CursorType = null;
            this.bunifuLabel11.Font = new System.Drawing.Font("Poppins SemiBold", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel11.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(84)))), ((int)(((byte)(93)))), ((int)(((byte)(142)))));
            this.bunifuLabel11.Location = new System.Drawing.Point(918, 33);
            this.bunifuLabel11.Name = "bunifuLabel11";
            this.bunifuLabel11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel11.Size = new System.Drawing.Size(54, 22);
            this.bunifuLabel11.TabIndex = 26;
            this.bunifuLabel11.Text = "00:00:00";
            this.bunifuLabel11.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel11.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Poppins SemiBold", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(84)))), ((int)(((byte)(93)))), ((int)(((byte)(142)))));
            this.bunifuLabel10.Location = new System.Drawing.Point(896, 13);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(76, 22);
            this.bunifuLabel10.TabIndex = 26;
            this.bunifuLabel10.Text = "0000/00/00";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnReset
            // 
            this.btnReset.AllowAnimations = true;
            this.btnReset.AllowMouseEffects = true;
            this.btnReset.AllowToggling = false;
            this.btnReset.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnReset.AnimationSpeed = 200;
            this.btnReset.AutoGenerateColors = false;
            this.btnReset.AutoRoundBorders = false;
            this.btnReset.AutoSizeLeftIcon = true;
            this.btnReset.AutoSizeRightIcon = true;
            this.btnReset.BackColor = System.Drawing.Color.Transparent;
            this.btnReset.BackColor1 = System.Drawing.Color.Crimson;
            this.btnReset.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnReset.BackgroundImage")));
            this.btnReset.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnReset.ButtonText = "Reset";
            this.btnReset.ButtonTextMarginLeft = 0;
            this.btnReset.ColorContrastOnClick = 45;
            this.btnReset.ColorContrastOnHover = 45;
            this.btnReset.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnReset.CustomizableEdges = borderEdges4;
            this.btnReset.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnReset.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReset.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReset.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReset.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Idle;
            this.btnReset.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.btnReset.ForeColor = System.Drawing.Color.White;
            this.btnReset.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReset.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnReset.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnReset.IconMarginLeft = 11;
            this.btnReset.IconPadding = 10;
            this.btnReset.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnReset.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnReset.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnReset.IconSize = 25;
            this.btnReset.IdleBorderColor = System.Drawing.Color.Crimson;
            this.btnReset.IdleBorderRadius = 15;
            this.btnReset.IdleBorderThickness = 1;
            this.btnReset.IdleFillColor = System.Drawing.Color.Crimson;
            this.btnReset.IdleIconLeftImage = null;
            this.btnReset.IdleIconRightImage = null;
            this.btnReset.IndicateFocus = false;
            this.btnReset.Location = new System.Drawing.Point(882, 115);
            this.btnReset.Name = "btnReset";
            this.btnReset.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReset.OnDisabledState.BorderRadius = 15;
            this.btnReset.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnReset.OnDisabledState.BorderThickness = 1;
            this.btnReset.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReset.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReset.OnDisabledState.IconLeftImage = null;
            this.btnReset.OnDisabledState.IconRightImage = null;
            this.btnReset.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(130)))), ((int)(((byte)(171)))));
            this.btnReset.onHoverState.BorderRadius = 15;
            this.btnReset.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnReset.onHoverState.BorderThickness = 1;
            this.btnReset.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(130)))), ((int)(((byte)(171)))));
            this.btnReset.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnReset.onHoverState.IconLeftImage = null;
            this.btnReset.onHoverState.IconRightImage = null;
            this.btnReset.OnIdleState.BorderColor = System.Drawing.Color.Crimson;
            this.btnReset.OnIdleState.BorderRadius = 15;
            this.btnReset.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnReset.OnIdleState.BorderThickness = 1;
            this.btnReset.OnIdleState.FillColor = System.Drawing.Color.Crimson;
            this.btnReset.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnReset.OnIdleState.IconLeftImage = null;
            this.btnReset.OnIdleState.IconRightImage = null;
            this.btnReset.OnPressedState.BorderColor = System.Drawing.Color.Crimson;
            this.btnReset.OnPressedState.BorderRadius = 15;
            this.btnReset.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnReset.OnPressedState.BorderThickness = 1;
            this.btnReset.OnPressedState.FillColor = System.Drawing.Color.Crimson;
            this.btnReset.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnReset.OnPressedState.IconLeftImage = null;
            this.btnReset.OnPressedState.IconRightImage = null;
            this.btnReset.Size = new System.Drawing.Size(90, 32);
            this.btnReset.TabIndex = 24;
            this.btnReset.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnReset.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnReset.TextMarginLeft = 0;
            this.btnReset.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnReset.UseDefaultRadiusAndThickness = true;
            // 
            // btnFilter
            // 
            this.btnFilter.AllowAnimations = true;
            this.btnFilter.AllowMouseEffects = true;
            this.btnFilter.AllowToggling = false;
            this.btnFilter.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnFilter.AnimationSpeed = 200;
            this.btnFilter.AutoGenerateColors = false;
            this.btnFilter.AutoRoundBorders = false;
            this.btnFilter.AutoSizeLeftIcon = true;
            this.btnFilter.AutoSizeRightIcon = true;
            this.btnFilter.BackColor = System.Drawing.Color.Transparent;
            this.btnFilter.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnFilter.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFilter.BackgroundImage")));
            this.btnFilter.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFilter.ButtonText = "Filter";
            this.btnFilter.ButtonTextMarginLeft = 0;
            this.btnFilter.ColorContrastOnClick = 45;
            this.btnFilter.ColorContrastOnHover = 45;
            this.btnFilter.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnFilter.CustomizableEdges = borderEdges5;
            this.btnFilter.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFilter.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFilter.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFilter.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFilter.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFilter.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.btnFilter.ForeColor = System.Drawing.Color.White;
            this.btnFilter.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFilter.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFilter.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFilter.IconMarginLeft = 11;
            this.btnFilter.IconPadding = 10;
            this.btnFilter.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFilter.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFilter.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFilter.IconSize = 25;
            this.btnFilter.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnFilter.IdleBorderRadius = 15;
            this.btnFilter.IdleBorderThickness = 1;
            this.btnFilter.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnFilter.IdleIconLeftImage = null;
            this.btnFilter.IdleIconRightImage = null;
            this.btnFilter.IndicateFocus = false;
            this.btnFilter.Location = new System.Drawing.Point(774, 115);
            this.btnFilter.Name = "btnFilter";
            this.btnFilter.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFilter.OnDisabledState.BorderRadius = 15;
            this.btnFilter.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFilter.OnDisabledState.BorderThickness = 1;
            this.btnFilter.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFilter.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFilter.OnDisabledState.IconLeftImage = null;
            this.btnFilter.OnDisabledState.IconRightImage = null;
            this.btnFilter.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(130)))), ((int)(((byte)(171)))));
            this.btnFilter.onHoverState.BorderRadius = 15;
            this.btnFilter.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFilter.onHoverState.BorderThickness = 1;
            this.btnFilter.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(130)))), ((int)(((byte)(171)))));
            this.btnFilter.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnFilter.onHoverState.IconLeftImage = null;
            this.btnFilter.onHoverState.IconRightImage = null;
            this.btnFilter.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnFilter.OnIdleState.BorderRadius = 15;
            this.btnFilter.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFilter.OnIdleState.BorderThickness = 1;
            this.btnFilter.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnFilter.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnFilter.OnIdleState.IconLeftImage = null;
            this.btnFilter.OnIdleState.IconRightImage = null;
            this.btnFilter.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnFilter.OnPressedState.BorderRadius = 15;
            this.btnFilter.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFilter.OnPressedState.BorderThickness = 1;
            this.btnFilter.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnFilter.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFilter.OnPressedState.IconLeftImage = null;
            this.btnFilter.OnPressedState.IconRightImage = null;
            this.btnFilter.Size = new System.Drawing.Size(102, 32);
            this.btnFilter.TabIndex = 23;
            this.btnFilter.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFilter.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFilter.TextMarginLeft = 0;
            this.btnFilter.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnFilter.UseDefaultRadiusAndThickness = true;
            // 
            // dataGridViewLaporan
            // 
            this.dataGridViewLaporan.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dataGridViewLaporan.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dataGridViewLaporan.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dataGridViewLaporan.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dataGridViewLaporan.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dataGridViewLaporan.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dataGridViewLaporan.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dataGridViewLaporan.ColumnHeadersHeight = 40;
            this.dataGridViewLaporan.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dataGridViewLaporan.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridViewLaporan.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridViewLaporan.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridViewLaporan.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dataGridViewLaporan.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dataGridViewLaporan.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridViewLaporan.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridViewLaporan.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dataGridViewLaporan.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dataGridViewLaporan.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dataGridViewLaporan.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dataGridViewLaporan.CurrentTheme.Name = null;
            this.dataGridViewLaporan.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dataGridViewLaporan.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dataGridViewLaporan.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dataGridViewLaporan.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dataGridViewLaporan.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dataGridViewLaporan.DefaultCellStyle = dataGridViewCellStyle3;
            this.dataGridViewLaporan.EnableHeadersVisualStyles = false;
            this.dataGridViewLaporan.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dataGridViewLaporan.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dataGridViewLaporan.HeaderBgColor = System.Drawing.Color.Empty;
            this.dataGridViewLaporan.HeaderForeColor = System.Drawing.Color.White;
            this.dataGridViewLaporan.Location = new System.Drawing.Point(314, 154);
            this.dataGridViewLaporan.Name = "dataGridViewLaporan";
            this.dataGridViewLaporan.RowHeadersVisible = false;
            this.dataGridViewLaporan.RowTemplate.Height = 40;
            this.dataGridViewLaporan.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dataGridViewLaporan.Size = new System.Drawing.Size(658, 192);
            this.dataGridViewLaporan.TabIndex = 17;
            this.dataGridViewLaporan.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Poppins SemiBold", 24F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(78)))), ((int)(((byte)(86)))), ((int)(((byte)(132)))));
            this.bunifuLabel2.Location = new System.Drawing.Point(314, 32);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(343, 56);
            this.bunifuLabel2.TabIndex = 16;
            this.bunifuLabel2.Text = "LAPORAN PENJUALAN";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Poppins SemiBold", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(84)))), ((int)(((byte)(93)))), ((int)(((byte)(142)))));
            this.bunifuLabel7.Location = new System.Drawing.Point(548, 87);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(59, 23);
            this.bunifuLabel7.TabIndex = 16;
            this.bunifuLabel7.Text = "Date End";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Poppins SemiBold", 26.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel8.Location = new System.Drawing.Point(91, 205);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(119, 62);
            this.bunifuLabel8.TabIndex = 20;
            this.bunifuLabel8.Text = "Admin";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox1.Image = global::csharp_lksmart.Properties.Resources.administrator_1;
            this.pictureBox1.Location = new System.Drawing.Point(74, 54);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(153, 145);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 14;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Poppins SemiBold", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(84)))), ((int)(((byte)(93)))), ((int)(((byte)(142)))));
            this.bunifuLabel3.Location = new System.Drawing.Point(314, 87);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(66, 23);
            this.bunifuLabel3.TabIndex = 16;
            this.bunifuLabel3.Text = "Date Start";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(101)))), ((int)(((byte)(133)))));
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.btnLogout);
            this.bunifuPanel2.Controls.Add(this.btnLogActivity);
            this.bunifuPanel2.Controls.Add(this.btnKelolaLaporan);
            this.bunifuPanel2.Controls.Add(this.btnKelolaUser);
            this.bunifuPanel2.Controls.Add(this.bunifuLabel8);
            this.bunifuPanel2.Controls.Add(this.pictureBox1);
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel2.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(300, 561);
            this.bunifuPanel2.TabIndex = 14;
            // 
            // btnKelolaUser
            // 
            this.btnKelolaUser.AllowAnimations = true;
            this.btnKelolaUser.AllowMouseEffects = true;
            this.btnKelolaUser.AllowToggling = false;
            this.btnKelolaUser.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnKelolaUser.AnimationSpeed = 200;
            this.btnKelolaUser.AutoGenerateColors = false;
            this.btnKelolaUser.AutoRoundBorders = false;
            this.btnKelolaUser.AutoSizeLeftIcon = true;
            this.btnKelolaUser.AutoSizeRightIcon = true;
            this.btnKelolaUser.BackColor = System.Drawing.Color.Transparent;
            this.btnKelolaUser.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnKelolaUser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnKelolaUser.BackgroundImage")));
            this.btnKelolaUser.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKelolaUser.ButtonText = "Kelola User";
            this.btnKelolaUser.ButtonTextMarginLeft = 0;
            this.btnKelolaUser.ColorContrastOnClick = 45;
            this.btnKelolaUser.ColorContrastOnHover = 45;
            this.btnKelolaUser.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnKelolaUser.CustomizableEdges = borderEdges6;
            this.btnKelolaUser.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnKelolaUser.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnKelolaUser.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnKelolaUser.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnKelolaUser.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnKelolaUser.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.btnKelolaUser.ForeColor = System.Drawing.Color.White;
            this.btnKelolaUser.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnKelolaUser.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnKelolaUser.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnKelolaUser.IconMarginLeft = 11;
            this.btnKelolaUser.IconPadding = 10;
            this.btnKelolaUser.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnKelolaUser.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnKelolaUser.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnKelolaUser.IconSize = 25;
            this.btnKelolaUser.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnKelolaUser.IdleBorderRadius = 15;
            this.btnKelolaUser.IdleBorderThickness = 1;
            this.btnKelolaUser.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnKelolaUser.IdleIconLeftImage = null;
            this.btnKelolaUser.IdleIconRightImage = null;
            this.btnKelolaUser.IndicateFocus = false;
            this.btnKelolaUser.Location = new System.Drawing.Point(64, 282);
            this.btnKelolaUser.Name = "btnKelolaUser";
            this.btnKelolaUser.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnKelolaUser.OnDisabledState.BorderRadius = 15;
            this.btnKelolaUser.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKelolaUser.OnDisabledState.BorderThickness = 1;
            this.btnKelolaUser.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnKelolaUser.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnKelolaUser.OnDisabledState.IconLeftImage = null;
            this.btnKelolaUser.OnDisabledState.IconRightImage = null;
            this.btnKelolaUser.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(130)))), ((int)(((byte)(171)))));
            this.btnKelolaUser.onHoverState.BorderRadius = 15;
            this.btnKelolaUser.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKelolaUser.onHoverState.BorderThickness = 1;
            this.btnKelolaUser.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(130)))), ((int)(((byte)(171)))));
            this.btnKelolaUser.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnKelolaUser.onHoverState.IconLeftImage = null;
            this.btnKelolaUser.onHoverState.IconRightImage = null;
            this.btnKelolaUser.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnKelolaUser.OnIdleState.BorderRadius = 15;
            this.btnKelolaUser.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKelolaUser.OnIdleState.BorderThickness = 1;
            this.btnKelolaUser.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnKelolaUser.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnKelolaUser.OnIdleState.IconLeftImage = null;
            this.btnKelolaUser.OnIdleState.IconRightImage = null;
            this.btnKelolaUser.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnKelolaUser.OnPressedState.BorderRadius = 15;
            this.btnKelolaUser.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnKelolaUser.OnPressedState.BorderThickness = 1;
            this.btnKelolaUser.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(90)))), ((int)(((byte)(133)))), ((int)(((byte)(170)))));
            this.btnKelolaUser.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnKelolaUser.OnPressedState.IconLeftImage = null;
            this.btnKelolaUser.OnPressedState.IconRightImage = null;
            this.btnKelolaUser.Size = new System.Drawing.Size(176, 39);
            this.btnKelolaUser.TabIndex = 15;
            this.btnKelolaUser.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnKelolaUser.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnKelolaUser.TextMarginLeft = 0;
            this.btnKelolaUser.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnKelolaUser.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Poppins SemiBold", 10F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(84)))), ((int)(((byte)(93)))), ((int)(((byte)(142)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(314, 12);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(127, 23);
            this.bunifuLabel1.TabIndex = 16;
            this.bunifuLabel1.Text = "Pages / Dashboard";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btnGenerate);
            this.bunifuPanel1.Controls.Add(this.chartOmset);
            this.bunifuPanel1.Controls.Add(this.dateEnd);
            this.bunifuPanel1.Controls.Add(this.dateStart);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel11);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel10);
            this.bunifuPanel1.Controls.Add(this.btnReset);
            this.bunifuPanel1.Controls.Add(this.btnFilter);
            this.bunifuPanel1.Controls.Add(this.dataGridViewLaporan);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel7);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel3);
            this.bunifuPanel1.Controls.Add(this.bunifuPanel2);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(984, 561);
            this.bunifuPanel1.TabIndex = 52;
            // 
            // chartOmset
            // 
            this.chartOmset.BackColor = System.Drawing.Color.Transparent;
            this.chartOmset.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.chartOmset.BackImageAlignment = System.Windows.Forms.DataVisualization.Charting.ChartImageAlignmentStyle.Top;
            this.chartOmset.BackImageTransparentColor = System.Drawing.Color.Transparent;
            this.chartOmset.BackSecondaryColor = System.Drawing.Color.Transparent;
            this.chartOmset.BorderlineColor = System.Drawing.Color.Transparent;
            chartArea1.Name = "ChartArea1";
            this.chartOmset.ChartAreas.Add(chartArea1);
            legend1.Name = "Legend1";
            this.chartOmset.Legends.Add(legend1);
            this.chartOmset.Location = new System.Drawing.Point(314, 352);
            this.chartOmset.Name = "chartOmset";
            series1.ChartArea = "ChartArea1";
            series1.Legend = "Legend1";
            series1.Name = "Series1";
            this.chartOmset.Series.Add(series1);
            this.chartOmset.Size = new System.Drawing.Size(658, 197);
            this.chartOmset.TabIndex = 28;
            this.chartOmset.Text = "chart1";
            // 
            // btnGenerate
            // 
            this.btnGenerate.AllowAnimations = true;
            this.btnGenerate.AllowMouseEffects = true;
            this.btnGenerate.AllowToggling = false;
            this.btnGenerate.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnGenerate.AnimationSpeed = 200;
            this.btnGenerate.AutoGenerateColors = false;
            this.btnGenerate.AutoRoundBorders = false;
            this.btnGenerate.AutoSizeLeftIcon = true;
            this.btnGenerate.AutoSizeRightIcon = true;
            this.btnGenerate.BackColor = System.Drawing.Color.Transparent;
            this.btnGenerate.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnGenerate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGenerate.BackgroundImage")));
            this.btnGenerate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerate.ButtonText = "Generate ";
            this.btnGenerate.ButtonTextMarginLeft = 0;
            this.btnGenerate.ColorContrastOnClick = 45;
            this.btnGenerate.ColorContrastOnHover = 45;
            this.btnGenerate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnGenerate.CustomizableEdges = borderEdges7;
            this.btnGenerate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGenerate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGenerate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGenerate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGenerate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnGenerate.Font = new System.Drawing.Font("Poppins SemiBold", 9F, System.Drawing.FontStyle.Bold);
            this.btnGenerate.ForeColor = System.Drawing.Color.White;
            this.btnGenerate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGenerate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGenerate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGenerate.IconMarginLeft = 11;
            this.btnGenerate.IconPadding = 10;
            this.btnGenerate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGenerate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGenerate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGenerate.IconSize = 25;
            this.btnGenerate.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnGenerate.IdleBorderRadius = 15;
            this.btnGenerate.IdleBorderThickness = 1;
            this.btnGenerate.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnGenerate.IdleIconLeftImage = null;
            this.btnGenerate.IdleIconRightImage = null;
            this.btnGenerate.IndicateFocus = false;
            this.btnGenerate.Location = new System.Drawing.Point(855, 392);
            this.btnGenerate.Name = "btnGenerate";
            this.btnGenerate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGenerate.OnDisabledState.BorderRadius = 15;
            this.btnGenerate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerate.OnDisabledState.BorderThickness = 1;
            this.btnGenerate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGenerate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGenerate.OnDisabledState.IconLeftImage = null;
            this.btnGenerate.OnDisabledState.IconRightImage = null;
            this.btnGenerate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(130)))), ((int)(((byte)(171)))));
            this.btnGenerate.onHoverState.BorderRadius = 15;
            this.btnGenerate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerate.onHoverState.BorderThickness = 1;
            this.btnGenerate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(81)))), ((int)(((byte)(130)))), ((int)(((byte)(171)))));
            this.btnGenerate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnGenerate.onHoverState.IconLeftImage = null;
            this.btnGenerate.onHoverState.IconRightImage = null;
            this.btnGenerate.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnGenerate.OnIdleState.BorderRadius = 15;
            this.btnGenerate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerate.OnIdleState.BorderThickness = 1;
            this.btnGenerate.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnGenerate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGenerate.OnIdleState.IconLeftImage = null;
            this.btnGenerate.OnIdleState.IconRightImage = null;
            this.btnGenerate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnGenerate.OnPressedState.BorderRadius = 15;
            this.btnGenerate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGenerate.OnPressedState.BorderThickness = 1;
            this.btnGenerate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(63)))), ((int)(((byte)(133)))), ((int)(((byte)(70)))));
            this.btnGenerate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGenerate.OnPressedState.IconLeftImage = null;
            this.btnGenerate.OnPressedState.IconRightImage = null;
            this.btnGenerate.Size = new System.Drawing.Size(102, 32);
            this.btnGenerate.TabIndex = 23;
            this.btnGenerate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGenerate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGenerate.TextMarginLeft = 0;
            this.btnGenerate.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGenerate.UseDefaultRadiusAndThickness = true;
            // 
            // FAdminLaporan
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(984, 561);
            this.Controls.Add(this.bunifuPanel1);
            this.Name = "FAdminLaporan";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form Laporan";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.KelolaFormLaporan_FormClosing);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridViewLaporan)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel2.PerformLayout();
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.chartOmset)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuDatePicker dateEnd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLogout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLogActivity;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnKelolaLaporan;
        private Bunifu.UI.WinForms.BunifuDatePicker dateStart;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel11;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnReset;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFilter;
        private Bunifu.UI.WinForms.BunifuDataGridView dataGridViewLaporan;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnKelolaUser;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartOmset;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGenerate;
    }
}